### ISSUE TITLE
가입약관 웹뷰로 붙이기

### ISSUE THREAD

**Issue by rlarlvy153** [wanna-go-home/Issue#146]

**Comment by yoowonyoung** [comment]
http://wy0105.iptime.org:8080/terms.html 이용약관 페이지임

**Comment by yoowonyoung** [comment]
http://wy0105.iptime.org:8080/termsOfPrivacy.html 개인정보 약관 페이지
http://wy0105.iptime.org:8080/termsOfUse.html 이용정보 약관 페이지

**Comment by rlarlvy153** [comment]
링크한개로 합쳐주세요
