### ISSUE TITLE
Server API versioning 추가하기

### ISSUE THREAD

**Issue by zamonia500** [wanna-go-home/Issue#149]

**Comment by yoowonyoung** [comment]
- 깃헙에 있는 release  / tag 기능을 통해서 버저닝 할 예정

**Comment by yoowonyoung** [comment]
- 지금 있는 ansible 템플릿을 dev  배포용으로 쓰고, 새 배포용 잡을 하나 만들어서, 걔는 저 깃헙에 태그 달린 저번으로 올릴수 있도록 해야할듯

**Comment by yoowonyoung** [comment]
끗남 ㅎ
