### ISSUE TITLE
댓글/대댓글 API 수정

### ISSUE THREAD

**Issue by up0617** [wanna-go-home/Issue#5]
게시물 activity : 댓글 프리뷰s
댓글 activity :  단일 댓글 전체

**Comment by yoowonyoung** [comment]
특정 글에 달린 댓글프리뷰(모든 댓글 + 대댓글 갯수 + 대댓글 0~3개 리턴) - /api/boards/free-board/{id}/comments
특정 댓글에 대한 모든 대댓글 리턴 - /api/boards/free-board/{id}/comment/{id}
